### ISSUE TITLE
a better chat matrix or how should to be.

### ISSUE THREAD

**Issue by AC-MPx** [assaultcube/AC#120]
http://i.imgur.com/oDyzS4n.png
Yeah, i made another of these graphic uml XD
Basically, if somebody is benched on a team, this should be able to communicate with his teammates by using the team chat. Key: Y

The current one don't allow to do that.

**Comment by aurhat** [comment]
Generally current system works so, with some exceptions:  SPECT-RVSF can't talk in team chat to RVSF, in order to SPECT-RVSF won't be able to give via AC discreetly hints (where is enemy, where is flag) to alive players from the team (of course the same situation with CLA). And all players from SPECT-CLA, SPECT-RVSF, and SPECTATOR are in common team chat, which looks good too. I don't see any other differences, maybe you will find some different exceptions. :)

I also see, that in non-team mode spectator uses team chat only with other spectators and alive players don't see these messages, but alive player always talk to all players - alive and spectators, probably that is ok too. :)
