### ISSUE TITLE
Make flag captures independent of player status.

### ISSUE THREAD

**Issue by Danfun64** [assaultcube/AC#132]
In the vast majority of fps games that have ctf mode, when a team captures a flag, it registers as captured, regardless of whether the player who did so switches teams or leaves. AssaultCube is the exception, and that isn't a good thing. For example, say on a ctf assaultcube server, the score is 10red-7blue, with one player on red having scored 6 times. If that player had a connection problem and was forced to disconnect, the score would become 4red-7blue. Bonus points if said player disconnects when there is only one minute left in the game. How is this fair?

I'm not sure if solving this issue is impossible or requires an extensive code rewrite, but if it can be done easily enough, it should be done before 1.3 is released.

**Comment by aurhat** [comment]
It's not a bug, it's a unique feature :). Sometimes can be annoying, but difficult to say, whether the change would be for the better. And then AC would stop to be unique, it would be as other FPS games. ;) 
In my opinion current solution should be improved, in order to limit negative effects (for example, scoreboard could be froze, at least final scores).

**Comment by Danfun64** [comment]
"It's not a bug, it's a unique feature"

I thought you would say that -.-

I take it that this isn't going to be "fixed" then...

**Comment by ac-stef** [comment]
Thing is - in pub games, flag scores are usually not the result of much teamplay, so it belongs to the player just as much as to the team. Also, as soon as players leave and others join, or as soon as they switch teams, the score doesn't mean much anyway. Which means that in pubs, the scoreboard can only be part of the result. To actually tell, who played best, you can only watch the demo - and there is no "fix" to change that. In your example, if the score went to the team, the scoreboard would look like the remaining red players scored 10 flags - which is clearly not true either.

Pubs are for-fun matches. Don't try to read deeper meaning into the scoreboards of pub games.

Arranged matches do not have that problem, since disconnected scores are kept and players usually don't switch teams during matches.
