### ISSUE TITLE
Malware scan of assaultcube_v1.2.0.2.exe

### ISSUE THREAD

**Issue by ghost** [assaultcube/AC#133]
Malware scan of assaultcube_v1.2.0.2.exe 

http://www.herdprotect.com/assaultcube_v1.2.0.2.exe-19dbe2695a46af6717f22fd537763d5d449f4b44.aspx

**Comment by DLHDragon** [comment]
also ...AVG antivirus ...list ...assaultcube_v1.2.0.2 files as unknown, medium-severity malware

**Comment by ac-stef** [comment]
AssaultCube_v1.2.0.2.exe as it can be downloaded from github or sf has the MD5 hash of bfeda85119761b0f95be3a420b51bbca, so that scan was not of our exe. There's a rumour of sf altering downloads on the fly - which is what may have happened here.

Also: AC is capable of running as a server, which some scanners may flag as "suspicious". Antivirus software is usually quite stupid.

**Comment by DLHDragon** [comment]
AssaultCube_v1.2.0.2.exe

 MD5 hash of BFEDA85119761B0F95BE3A420B51BBCA

SHA-1 hash of 6198E14DAB2048AD954A65D49FC2675BF546EB72

when AssaultCube_v1.2.0.2 is run after it is installed, AVG antivirus blocks it and tell you that it is an unknown, medium-severity malware...it list all the files in ( bin_win32 ) folder...

NOTES:
- this DOES NOT happen with  AssaultCube_v1.2.0.1 when it is started / run after it is installed...

**Comment by ac-stef** [comment]
Well, if you insist on running crappy AV software and also refuse to ignore false alarms of said crappy AV software, I recommend to delete the exe and compile it for yourself. The forum has a few nice guides on how to do so.

Also: the only files in bin_win32 that changed between 1.2.0.1 and 1.2.0.2 were the two exe files. So, if no files of 1.2.0.1 get flagged, but all of 1.2.0.2 - well, as I said, crap software...
