### ISSUE TITLE
Make /pm truely private

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#135]
It appears `/pm` is not really private, it is other clients that hide `/pm` messages from users when is not directed to them.

**Comment by ac-stef** [comment]
The server transmits the message only to the intended target.

**Comment by GreenLunar** [comment]
If AC uses IRC to chat, your statement is likely wrong.

I have seen, more than once, the following occurrence when a player sends me a private message.

PlayerA sends to PlayerB a private message as follows:

PlayerA (PM): I think PlayerC is using an aimbot
PlayerC: no
to PlayerA: How can you tell?
PlayerA (PM): PlayerC has respond to the PM that I just sent to you

**Comment by ac-stef** [comment]
Game clients only communicate via game server. A private message is sent to the server. The server writes a log entry and (if permitted) sends the message to the receiving player.

So:
- the message is not "secret", since the server owner can read it in the logs
- no other game client receives the message
- the message is not written to the demo file (while team-text messages are)

All of this works exactly as intended.

Your scenario is possible, if PlayerC has realtime access to the server logs. This can not be "fixed", since log entries of private messages are a feature, not a bug.

Btw, neither client nor server use IRC in any way. Text communication is part of the game protocol. D'oh!

**Comment by GreenLunar** [comment]
Thank you for your answer.

> the message is not written to the demo file (while team-text messages are)

Is there such thing as admin demo? (a demo that does have PM messages logged)

> Btw, neither client nor server use IRC in any way. Text communication is part of the game protocol.

A assumed protocol IRC due to players claiming that AC uses IRC protocol to chat, and I even was kicked after I asked for a reference.
