### ISSUE TITLE
disconnects regularly on debian

### ISSUE THREAD

**Issue by Gip-Gip** [assaultcube/AC#156]
AssaultCube disconnects frequently when playing multiplayer. I did not have this issue on puppy linux.
here's the error:

```
server network error, disconnecting (normal) ...
disconnected
```

**Comment by areynoua** [comment]
Do you use AC from repos, from [assault.cubers.net](http://assault.cubers.net/) or from github?

**Comment by Gip-Gip** [comment]
From the website

**Comment by ac-stef** [comment]
"disconnecting (normal)" is the external loss of connection, due to some connection problem. For example, it's what you see, if the server crashes. Maybe some traffic shaping router or overload condition squeezes out your UDP packets? How busy is your line?

**Comment by Gip-Gip** [comment]
It depends on the time of day. During the night, when I normally play AssaultCube, it's usually the only thing taking up bandwidth. I'll check for any suspicious background programs.

**Comment by Gip-Gip** [comment]
UPDATE: closing rTorrent does help keep this error from occurring(I don't know why), but I found it's fairly frequent when playing LAN games(with someone else hosting).

Plus, a couple questions:
why do interruptions cause this error(why doesn't AssaultCube reconnect), and why does AC not use TCP(there shouldn't be a huge speed difference, the connection is bidirectional I assume)

**Comment by ac-stef** [comment]
You are aware, that this is a online multiplayer game where (low) network latency is key? The game server expects a position update from your client every 40 milliseconds - which requires a fairly unloaded internet connection. To get disconnected "normal", the connection has to be virtually dead for several seconds. You can't play with that kind of connection.

Do NOT run any downloads while you play AC (or any other online game) and especially no filesharing clients, since they usually completely saturate your uplink bandwidth.

Even if you don't get disconnected, you most certainly lag horribly. You lag to other players and other players lag for you - which means, the whole game is jumpy and unplayable. BTW, you are ruining the game for the other players, too - so, in addition to the "normal" disconnects, you should expect some "kicked" as well.

During play: do not run servers, do not download, no filesharing, do not use VPN relays or proxies.
Use cable connections, not wireless. Play on servers near you (that is: have low ping).

If you still think, some of the disconnects are caused by the game, try playing the game sauerbraten - it uses a very similar network structure. If sauerbraten works fine but AC keeps disconnecting, /then/ you have an issue to file here :)

**Comment by Gip-Gip** [comment]
My ping is ~100 when I get kicked. I doubt that is the issue.
