### ISSUE TITLE
bot survival forces edit mode on 

### ISSUE THREAD

**Issue by amdcrash** [assaultcube/AC#169]
so i can not play that mode

**Comment by aurhat** [comment]
How to reproduce it?

**Comment by ac-stef** [comment]
Is that with 1.2.0.2 or with some version from the repository? Which branch?

**Comment by amdcrash** [comment]
All I know is that it is the portable apps version

**Comment by ac-stef** [comment]
We don't have a portable app version. Where did you get it from?
btw. I'm pretty sure, that an installation with our installer onto a drive (choose a path and "XP-Mode" during installation) is also portable...

To check, if only some parameter was changed and causes problems, please run a test with a clean profile directory (just rename the existing one) - whereever that portable app puts it. (The profile directory is the place where screenshots and demos go and where config/saved.cfg is stored. Just rename it, so that AC can't find it and creates an empty one.)

**Comment by amdcrash** [comment]
https://portableapps.com/apps/games/assaultcube_portable
I do not have the current version Number as I am not near my computer at this time
