### ISSUE TITLE
Map doesn't display correctly

### ISSUE THREAD

**Issue by Noah11012** [assaultcube/AC#174]
A map called assault_camper won't display properly.
![screenshot from 2017-07-17 16-18-24](https://user-images.githubusercontent.com/26338478/28288095-0739116c-6b0c-11e7-8a86-439092045d8a.png)

That is how it's suppose to be rendered.

This is how it's being rendered. Which is wrong.

![screenshot from 2017-07-17 16-20-07](https://user-images.githubusercontent.com/26338478/28288167-47ca4df4-6b0c-11e7-98a6-dc9e057d2651.png)

It also gives a warning of "unresolved problems occurred during load_world(), warning: 0x1"

Any ideas what might be causing it?

**Comment by ac-stef** [comment]
You could have read one of the several dozen other warning messages during the laod of a camper map: "overflow during conversion of attr3 of entity (mapmodel): value can no longer be represented - pls fix manually before saving the map".

The new map format changed the encoding of some map entity attributes to increase their resolution - which also reduced their allowed maximum value. If an old map is loaded and an attribute can't be converted because it no longer fits the attribute, a warning is printed. The map then has to be fixed manually.

This is not really an issue, since proper maps rarely use attribute values that no longer fit. I know that, because I fixed all maps that are on akimbo (~ 600 maps). Crappy maps like camper, which are designed to break all rules of AC mapping, may be harder to fix. Bummer!

**Comment by Noah11012** [comment]
@ac-stef Thanks for your help!
