### ISSUE TITLE
New tagged release

### ISSUE THREAD

**Issue by Justinzobel** [assaultcube/AC#177]
As the current "release" is over 2 years old it might be time to release a new version 1.2.0.3 or 1.3 etc to allow Linux distributions to update without using a random git tag.

**Comment by ac-stef** [comment]
Distributions need to stick with the official releases. While, for example, the current master is still able to connect to servers from the 1.2.0.2 release, it is not designed to be fully compatible. Coopedit would not work at all, but what's much worse, there are several severe changes in the physics engine, which in some cases may allow to reach parts of a map that the 1.2.0.2 client can not reach.

In short: if you want to distribute our game, you have to stick with our official releases. Do not "make up" your own intermediate releases!

In fact, I would recommend that you drop by on IRC (#assaultcube on quakenet) for a little chat before *every* package release. While we are happy to see the game spread - creating a working AC package is quite tricky and we are happy to help. Also, since our IRC channel is among the first places where players come to look for help, it helps our support efforts to know about new (and therefore possibly buggy) packages out there...

**Comment by Justinzobel** [comment]
Thanks I'll stop by the channel on your next release to look at packaging it.
