### ISSUE TITLE
Awp Damage (very sadge must ooga)

### ISSUE THREAD

**Issue by FestiveSS** [assaultcube/AC#236]
Make it so that the closer you are to the enemy, the more damage the awp (or every single weapon) will dealt

**Comment by blehmeh98** [comment]
This isn't Counter-Strike. It's not an AWP that has to compete with an M4, an AK, etc. It's a Sniper Rifle that needs to be viable and carve out a unique niche among the Carbine, the Assault Rifle, the SMG, and the shotgun. 

The sniper rifle already has a unique niche where if you shoot someone in the head, they die instantly, and you get credited with two frags instead of one.

If you want a long range weapon with good DPS, the carbine should be your go-to. Land shot after shot with this thing from far away, and you can put down players faster than they can run in. I especially love using this thing on flag defense on Laino because of how busted it is at a distance.

However, the sniper rifle is the more refined option for if you can hit a headshot, especially in game modes where you win by amassing a larger score than your opponent, since a headshot with the Sniper Rifle in Assault Cube is worth two frags instead of one. 

Alternatively, switch to your pistol between shots to finish off the enemy. I've fought against snipers who use this tactic both from far away and up close, and it's pretty dangerous to fight a sniper who carves out a large chunk of your health with a good shot and then finishes you off with the handgun, or shoots you a few times with the handgun to further weaken you and then shoots you with the sniper rifle again. 

Given this, I think that the weapons are balanced as is.
