### ISSUE TITLE
[release_1.3_alpha1] Ladder doesn't work as expected 

### ISSUE THREAD

**Issue by elmillion** [assaultcube/AC#281]
On ac_desert's ladder if you go too much to the right or to the left you get stuck. That wasn't the case in 1.2

@BrutalSystem wrote : "The reason this happens now is that the corners now in AC really work like corners, so you’re going more to the side now."

**Comment by drian0** [comment]
I see two options: 

- Either we leave it as-is. 
- Or we add clips at the left/right side of ladders to mitigate this.

I will add more people to the loop.

**Comment by cf-1984** [comment]
This is indeed caused by the different collusion of corners, giving away more space left and right of the ladder in that particular map and spot. Now players can move right up to the wall between the corners and the mapmodels default clip in the middle of the ladder. 

Suggested fix:
Set the mapmodel clip setting on slot #9 to 0. This clip isn't needed for the ladder entity to operate properly.

+ Positive side effect: It will be slightly easier to jump down the well.
- Negative side effect: Might look weird in third person (ladder overlapping with player), but negligible for that particular spot

**Comment by BrutalSystem** [comment]
![20210428_20 10 38_ac_desert_coop](https://user-images.githubusercontent.com/7694535/116466429-d7ff3000-a844-11eb-8406-f00986a40fea.jpg)
solution, just add a clip on the left side

**Comment by drian0** [comment]
@BrutalSystem Could you check with Halo and Floppy if this fix is the way to go? If so, let us fix all maps.

**Comment by drian0** [comment]
@BrutalSystem Could you provide a short update on this one?

**Comment by BrutalSystem** [comment]
all ladders have been fixed.

**Comment by drian0** [comment]
Thanks!
