### ISSUE TITLE
[release_1.3_alpha1] coop is broken in multiplayer

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#297]
when sending map to the server always appears rev 0
map sent: sometimes it works calls vote / coop other times it doesn't work, it says that the server doesn't have the map even if you sent it
using / getmap you don't get the map from the server normally

**Comment by flowtron** [comment]
COOP should be tested intensively before the release; the sendmap issue should already have been dealt with in commit 54f7309 but other issues may still linger! 

Previous settings seem to have tried to make COOP be something only possible on special servers that took care to be set up to allow it; since it's such a great feature I feel it should be allowed until marked as unwanted. I can understand that servers meant for league play or similar competitive scenarios may want to disable it - they can and it's documented how - but a newcomer that wants to host a quick mapping session on their LAN-party shouldn't have to fiddle around with -P and -M switches.

**Comment by BrutalSystem** [comment]
send map to server, there is a delay for you to vote this map.

this is because now server checks maps whenever someone is logged into server, i don't know how long it takes server to check again, so after the map is uploaded to the server there should be a map check sent so you can vote this map after send.

servers checking maps
![servers checking maps)](https://user-images.githubusercontent.com/7694535/122484337-c6b3e380-cfaa-11eb-85f9-202c4a32ff13.png)

**Comment by flowtron** [comment]
There is no more wait - that has been take care of in [commit 54f7309](https://github.com/assaultcube/AC/commit/54f730942351b090fa521c316396036563b81224) - see line 668 in serverfiles.h where it says "triggerpollrestart = true" - that makes the server re-evaluate the available maps as soon as the upload is done!

**Comment by BrutalSystem** [comment]
> There is no more wait - that has been take care of in [commit 54f7309](https://github.com/assaultcube/AC/commit/54f730942351b090fa521c316396036563b81224) - see line 668 in serverfiles.h where it says "triggerpollrestart = true" - that makes the server re-evaluate the available maps as soon as the upload is done!

oh, ok, i used an outdated version sorry :)

**Comment by BrutalSystem** [comment]
> when sending map to the server always appears rev 0
still unresolved.
