### ISSUE TITLE
[release_1.3]if you press right-click while holding down left click, you stop shooting

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#304]

**Comment by drian0** [comment]
A potential fix is commented here. The fix is not functioning properly yet as @BrutalSystem pointed out in the comments.
https://github.com/assaultcube/AC/commit/7a26c9dfaaec2069ec302f6e7cf402be0eece6f6

This two videos show the remaining issue:
https://drive.google.com/file/d/1GeUATCLlkg-6ZjIPduzHAA870K8e-dCi/view?usp=sharing
https://drive.google.com/file/d/16vjvA1tq7tQC0VKJn1vOE4oAv7mzRUlD/view
