### ISSUE TITLE
[release_1.3_beta1] Hide entity sparklies & entity selection (pointatent) is reset whenever AC is closed

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#362]

**Comment by flowtron** [comment]
I've added some GUI display for the hideentmask - because I see the persistence as a double edged sword. If your are an avid mapper you may have some favourite grouping, sure. But if you just toyed around with the mask settings and return to editing after some time you may be suprised to not see any light entities. There is now a "showeditingsettings" variable, which is currently only showing the edithideentmask but may be used for more extra HUD info in the future. Even at 0 it will show the bitmask at first edittoggle after loadmap if(!) it isn't "all on" - that should jog your memory without cluttering the HUD too much.

The pointatent value is now permanent too, the HUD text is smaller now and it shows up separately for pinned/point-at/closest.

**Comment by BrutalSystem** [comment]
**fixed entity selection (pointatent) is reset whenever AC is closed** https://github.com/assaultcube/AC/pull/366
