### ISSUE TITLE
[release_1.3_beta1] bug after generating a new clip after copying clip size from nearest entity

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#363]
when pick clip size from closest entity and generating a new clip with just a change in one  ATTR the other values are kept. this is directly related to copying clips with support for new values an example is clip: 0, 5, 4.8, 0

[It's hard for me to explain it in words, so I think with a video someone will understand what I mean.](https://drive.google.com/file/d/1zDWUsj6GOtDCieAPbXvGWJEVy9M21fkO/view?usp=sharing)

after place clip entity values have to be reset.

**Comment by flowtron** [comment]
menus keep their state - so this is a more general issue, not just pertaining to clips. TBH I haven't used the "pinned" feature myself, not a big mapper in (Cube1/)AssaultCube; I'm irritated by the fact the sliders show values of 4 5 5 and the entity values are 4.0 5.6 5.0 .. but that's not you're problem!?! At what point would you say the values in the menu should be reset .. and to what? 0 0 0 .. wouldn't that lead to people complaing they have to keep setting the dimensions to the same values repeatedly because of the "fix-is-new-bug reset" ?? Aren't you most likely to set a number of clips that share at least one dimension, or just need an increment here or there?

**Comment by BrutalSystem** [comment]
> I'm irritated by the fact the sliders show values of 4 5 5 and the entity values are 4.0 5.6 5.0 .. but that's not you're problem!?! 

clips now have supported for new sizes; example 1.2, 1.4, 1.6, 1.8

> At what point would you say the values in the menu should be reset .. and to what? 0 0 0 .. wouldn't that lead to people complaing they have to keep setting the dimensions to the same values repeatedly because of the "fix-is-new-bug reset" ?? Aren't you most likely to set a number of clips that share at least one dimension, or just need an increment here or there?

you're right about resetting to 0 0 0 , so after using "pick clip size from closent" and using "place clip entity" entity value becomes an integer.

**Comment by flowtron** [comment]
I've worked on this in commit 8a28e180562c85dedfd9c62aa5a76d21d3f7c7e8 : The sliders will keep their values indefinitely, that is a feature; the decimal issue didn't sit right with me though. Without some considerable work on the menu system decimal point values aren't supported, so I've decided to indicate that the first 5 sliders are displayed x10 - the copying of the closestent values works now too. So it's an improvement even if it's not a perfect solution.
