### ISSUE TITLE
[release_1.3_beta1]bug with editent/entset

### ISSUE THREAD

**Issue by BrutalSystem** [assaultcube/AC#376]
[**changing attr values using editent/entset ends up changing values of another attr**](https://drive.google.com/file/d/1nGSn_O-SvSQGJjiFN8ckb3zc1fkUoMX2/view?usp=sharing)

**Comment by BrutalSystem** [comment]
should not change the "angle" again, the angle is always automatically updated because the angle is taken using the position you are viewing

**Comment by flowtron** [comment]
There is more going on here than the angle – you were only using the values 90 and 20, this may have mislead you. When I try it out and set some values by hand in the entset command the values are taken .. I hit the editent-key and that shows the values too .. but if I simply hit ENTER then all entity attributes after the 4th get set to 0. There must be some confusion between the old 4-attr only entities and the new 7-attr entities in the code - I'll go hunting for it!

**Comment by flowtron** [comment]
fixed in https://github.com/assaultcube/AC/commit/fad77cbbd341682ac42aa9254629f08653fbbdc8

**Comment by BrutalSystem** [comment]
@flowtron i think editent shouldn't update angle because i see the function is to edit entity, adjust attrs values, i found this problem when i was updating maps, adjusting attr values so mapmodel's angle was changed automatically, i could have changed several mapmodels accidentally, image you always have to adjust the angle again whenever you use editent.

**Comment by flowtron** [comment]
Heh! I started typing the same concern before watching the video; using editent/entset with mapmodels is kind of stupid: yes!
But since you can simply use **MW+#** (MW+1, MW+2, …) to tweak individual attributes .. that is the way I do it.
I'm not saying it couldn't be done (in theory) but there is a workaround (or rather: better way) and the way **entset** works under the hood is based on **newent**, which in turn brings along the "take player yaw for angle" which was considered a nice feature - face the way you want the player to look when spawing while placing a spawn .. no need to know the way angle-0° points (the arrow pointing in the angle direction was only added in 1.0 or 1.1).
