### ISSUE TITLE
Request to add EOS Anti-Cheat

### ISSUE THREAD

**Issue by hassanbenhzaine** [assaultcube/AC#478]
I'm asking to work on adding EOS Anti-Cheat as an anti-cheat solution for AssaultCube. EOS Anti-Cheat is a free and effective anti-cheat solution used by a variety of popular games. This is a kernel-mode driver that provides a high level of cheat protection in multiplayer games.

Currently I think this game is very good project  but the fact that anyone can cheat makes it less fun and this project should be about showing the big commercial companies that just a community of developers/desginer/artists... can makea game not only fast and optimized but secure againt cheating.

Check out this page for more details:

https://dev.epicgames.com/docs/game-services/anti-cheat

**Comment by RealPacket** [comment]
Good luck hoping that people aren't going to `git revert` the commit!

**Comment by RealPacket** [comment]
You can thank me for making a meme out of you.
![image](https://github.com/assaultcube/AC/assets/107498533/247917c3-ec86-4533-b6b1-b59d40e6031c)

**Comment by hassanbenhzaine** [comment]
everyone is laughing at me i'm just trying to make game more fun lol

**Comment by RealPacket** [comment]
> everyone is laughing at me i'm just trying to make game more fun lol

it's an open source project, adding a AntiTamper on the client won't work at all

**Comment by RealPacket** [comment]
+ this game is really only known because of people making game hacking videos on it. Adding an AntiTamper (assuming most people wouldn't just update their tutorials to use a Kernel driver) would make the game less popular.

**Comment by RealPacket** [comment]
and because the game's server code is open source, you could also look at how it responds to packets and how its network works and easily make a game client.
the game also seems to have an anticheat on the server (if you enable it with the flag "ACAC"), however, it includes a file called "anticheat.h", which I couldn't find in the git repo so probably not done yet or a scrapped idea still in the repo.

**Comment by RealPacket** [comment]
and because the game's server code is open source, you could also look at how it responds to packets and how its network works and easily make a game client.
the game also seems to have an anticheat on the server (if you enable it with the flag "ACAC"), however, it includes a file called "anticheat.h", which I couldn't find in the git repo so probably not done yet or a scrapped idea still in the repo.
https://github.com/assaultcube/AC/blob/13f0d8eea4822dee5c976661218d022be74342e3/source/src/serverchecks.h#L26-L28

**Comment by RealPacket** [comment]
plus I also said 2 days ago:

> Good luck hoping that people aren't going to `git revert` the commit!

Now I have reasoning to laugh at you. People would just revert, you could make a breaking protocol change or just let the servers upgrade to a new protocol version,
but people would just reverse engineer the protocol or just look at the source code.
There's no point in making a "solution" when the solution is to stop whining and get some god damn moderators and/or a server sided AntiCheat.
Most people who don't have experience with any reverse engineering (probably you) think that Kernel AntiTampers are the end of the world for cheating,
it's not, in fact, people doing something to try and prevent you from doing X will usually just see more people trying to
bypass their prevention and keep doing X (or at least this should happen).

**Comment by hassanbenhzaine** [comment]
@RealPacket I don't mind if you laugh at me I'm just trying to make game better but seems It wouldn't work based on what you said
