### ISSUE TITLE
BTDM on multiplayer

### ISSUE THREAD

**Issue by RandumKiwi** [assaultcube/AC#54]
http://i.imgur.com/0fhZtbe.png

MPx found this... it's was done by my server accidentally due to a bug in the script that randomises the maprot. Please fix AC so that non-multiplayer modes can't be set in the maprot.

**Comment by GreenLunar** [comment]
BTDM on multiplayer may be great, on some occasions, even though bots are pretty incompetent on DM (e.g. not picking health packs when their level of health is critically low).

**Comment by AC-MPx** [comment]
I tested on a LAN server, once you have been killed by a bot, you can not respawn and the bots keep running like idiots without shooting. XD
It's very simple. the server should ignore the entries on the maprot of the following modes:
7 BTDM
8 BDM
12 BOSOK

**Comment by ac-stef** [comment]
When the maprot code was written, the general assumption was, that a server owner knows what he's doing. That's why there are very few checks on the entries. For example, you can also put "ctf desert" in your maprot - even if that does not make any sense.

By now, I know better about the average server owner, so I would consider this a bug ;)

However, the maprot code is about to be removed, so I won't bother fixing it. The replacement will be rule-based and not have this bug.

BTDM will not work in multiplayer, simply because the server does not contain the bot AI. You could try running a client binary as dedicated server, but afaik the bot positions are not distributed - AC bot modes are simply not meant to run in multiplayer.

**Comment by AC-MPx** [comment]
yeah, but what about if some server owner place a custom map with no flags entities and then edit the maprot adding that map to be played on ctf. The server will detect that there's no flags and call a vote for the next map instead of keep the people playing there with some kind of "ctf/tdm" ?

**Comment by drian0** [comment]
My understanding is that this is corrected in v1.3

**Comment by GreenLunar** [comment]
When will v1.3 be release?

**Comment by ac-jamz** [comment]
Tuesday the 14th of When It's Ready. Don't ask stupid questions in closed bug reports, thanks, GreenLunar.
