### ISSUE TITLE
Disable figure reflection and shadow in single edit mode

### ISSUE THREAD

**Issue by GreenLunar** [assaultcube/AC#71]
While editing, when getting in front of water, user can see a reflection of AC figure.  This does not make sense.

**Comment by GreenLunar** [comment]
@ac-stef does this commit disables shadows for both single-player and multi-player modes, or just for single-player mode?

**Comment by ac-stef** [comment]
it disables water reflections whenever the edit mode is selected - regardless of the network status

**Comment by GreenLunar** [comment]
Not good. I prefer to have the previous state, and forget about this issue.

**Comment by ac-stef** [comment]
did you read the commit message?

**Comment by GreenLunar** [comment]
Yes, and I have also read the code, which does not seen to distinguish single/multiplayer modes, and that is why I have asked the question above.

**Comment by ac-stef** [comment]
As the commit message states, the reflection is disabled during editing, because it disturbs the visibility of the editing grid - which is needed for editing. The editing mode is for editing maps.

If the reflection of someone else should be visible in editing mode is completely irrelevant - and certainly not an "issue" whatsoever.

(I did not write the commit with this pseudo issue in mind - which is why i had to amend the commit message to reference it.)
